// Copyright (C) 2026 Orhan Özşahin — Asdamir.
// Licensed under the GNU Lesser General Public License v3.0. See LICENSE.
// SPDX-License-Identifier: LGPL-3.0-or-later
//
// This file is part of the Asdamir open core. It is free software: you can redistribute it
// and/or modify it under the terms of the GNU Lesser General Public License as published by the
// Free Software Foundation, either version 3 of the License, or (at your option) any later
// version. It is distributed WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU LGPL for more details.

using System.Buffers.Binary;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;

namespace Asdamir.Core.AgentAudit;

/// <summary>
/// Builds the FROZEN canonical byte serialisation that the agent action ledger's hash chain is computed over —
/// canonicalization <b>version 1</b>.
///
/// <para><b>This type is the single most change-sensitive thing in the feature.</b> Every hash ever written is
/// a function of these bytes, so a "harmless tidy-up" here silently invalidates the entire history: rows that
/// were never touched stop verifying. The layout is therefore FROZEN per <see cref="HashVersion1"/> and pinned
/// by committed golden vectors that were generated by an INDEPENDENT implementation. If a change is genuinely
/// needed, it takes a NEW <see cref="IAgentActionCanonicalizer.HashVersion"/> — old rows keep verifying under
/// theirs — never an edit to an existing one.</para>
///
/// <para><b>Why it is PUBLIC.</b> A folded range leaves the live database and survives only as an archive. If
/// the only code able to re-derive those bytes were the closed component that produced them, the assurance
/// would collapse to "trust the vendor" — a system's own clean report about itself is not audit evidence. It is
/// open core so an archive can be verified without the product, without a database and without a licence. The
/// specification (<c>docs/fundamentals/agent-audit-canonicalization-v1.md</c>) plus the published golden vectors
/// remain the normative contract; this class is one conforming implementation of it, not the definition.</para>
///
/// <para><b>Static algorithm, instance interface — both on purpose.</b> The layout is a pure function over
/// frozen bytes: no state, no configuration, no policy, nothing to substitute. So the algorithm is exposed as
/// STATIC members, which is also how every existing call site uses it. <see cref="IAgentActionCanonicalizer"/>
/// is implemented EXPLICITLY on top of them for the one thing an interface is genuinely needed for — version
/// dispatch, where a verifier must select an implementation by the record's stored <c>HashVersion</c> instead
/// of assuming the newest. Use <see cref="V1"/> when you need the instance.</para>
///
/// <para><b>Hybrid by design.</b> This builds SEGMENT A only (fields 1-23, everything the client knows). The
/// two fields only the server can know — SeqNo and the server-side RecordedAt — are appended by
/// <c>dbo.AgentActionLedger_Append</c> while it holds the per-chain lock. That is what makes the sequence race
/// unwinnable outside the database.</para>
///
/// <para><b>Where the WRITE path runs.</b> Server-side, in the control plane, not in the calling application:
/// field 2 is the AppId, and the AppId is resolved from the ingest service token rather than from the payload,
/// so the client is structurally unable to build its own prefix.</para>
/// </summary>
public sealed class AgentActionCanonicalizer : IAgentActionCanonicalizer
{
    /// <summary>The only canonicalization version in existence. Its layout must never change.</summary>
    public const byte HashVersion1 = 1;

    /// <summary>RecordKind 0 — an ordinary agent action event.</summary>
    public const byte RecordKindEvent = 0;

    /// <summary>
    /// The shared v1 instance, for callers that need <see cref="IAgentActionCanonicalizer"/> rather than the
    /// static algorithm. Stateless, so one instance serves every thread.
    /// </summary>
    public static AgentActionCanonicalizer V1 { get; } = new();

    /// <summary>A chain's first row is anchored on 32 zero bytes.</summary>
    public static ReadOnlySpan<byte> ZeroHash => new byte[32];

    /// <inheritdoc />
    public int HashVersion => HashVersion1;

    /// <summary>
    /// Builds segment A for <paramref name="record"/> in the chain scoped to <paramref name="appId"/> — the
    /// WRITE path, where canonical field 6 is formatted from a <see cref="DateTime"/>.
    /// </summary>
    /// <param name="appId">The chain's application id — resolved server-side, never taken from the payload.</param>
    /// <param name="record">The action being recorded.</param>
    /// <param name="recordKind">0 = Event, 1 = Seal. Tombstones carry no prefix at all.</param>
    /// <param name="hashVersion">The canonicalization version; the first byte of the result, which the
    /// stored procedure cross-checks against its own parameter so a wiring bug cannot poison a chain.</param>
    /// <returns>The canonical prefix bytes.</returns>
    public static byte[] BuildPrefix(
        Guid appId, AgentActionRecord record, byte recordKind = RecordKindEvent, byte hashVersion = HashVersion1)
    {
        ArgumentNullException.ThrowIfNull(record);

        return BuildCore(
            hashVersion, appId, record.TenantId, recordKind, record.EventId, RoundTrip(record.OccurredAtUtc),
            record.AgentId, record.AgentVersion, record.ModelId, (byte)record.AuthorityKind,
            record.OnBehalfOfUserId, record.SessionId, record.InvocationId, record.CorrelationId,
            record.ActionType, record.TargetType, record.TargetId, (byte)record.Decision, (byte)record.Outcome,
            record.InputDigest, record.OutputDigest, record.ErrorCode, record.ErrorDigest);
    }

    /// <summary>
    /// Rebuilds segment A from an archive row's OWN COLUMNS — the VERIFY path.
    ///
    /// <para>Canonical field 6 is taken as the row's literal <see cref="AgentLedgerArchiveRow.OccurredAtUtc"/>
    /// TEXT, not re-formatted from a parsed instant: the format hashes that exact UTF-8 text, and a verifier
    /// that reformats would report an intact archive as broken the moment its runtime's formatter disagreed
    /// with the producer's by a single character.</para>
    ///
    /// <para><see cref="AgentLedgerArchiveRow.CanonicalPrefix"/> is deliberately NOT read here. Re-hashing the
    /// stored prefix is circular — it is exactly why an in-database check cannot see an edited projection
    /// column, and the archive layer must not import that weakness.</para>
    /// </summary>
    /// <param name="row">The archive row. Its hex members must already be well-formed; malformed hex throws
    /// <see cref="FormatException"/>, which the archive verifier prevents by validating shape first.</param>
    /// <returns>The canonical prefix bytes as this row's columns produce them.</returns>
    public static byte[] BuildPrefix(AgentLedgerArchiveRow row)
    {
        ArgumentNullException.ThrowIfNull(row);

        return BuildCore(
            checked((byte)row.HashVersion), row.AppId, row.TenantId, checked((byte)row.RecordKind), row.EventId,
            row.OccurredAtUtc, row.AgentId, row.AgentVersion, row.ModelId, checked((byte)row.AuthorityKind),
            row.OnBehalfOfUserId, row.SessionId, row.InvocationId, row.CorrelationId, row.ActionType,
            row.TargetType, row.TargetId, checked((byte)row.Decision), checked((byte)row.Outcome),
            FromHex(row.InputDigest), FromHex(row.OutputDigest), row.ErrorCode, FromHex(row.ErrorDigest));
    }

    /// <summary>
    /// Recomputes a row hash: <c>SHA-256(PrevHash || prefix || SeqNo(BE8) || RecordedAtTicks(BE8))</c>. Used by
    /// the canonical verifier; the appending procedure computes the identical value in T-SQL.
    /// </summary>
    /// <param name="prevHash">The previous row's hash (32 bytes), or 32 zero bytes for a chain's first row.</param>
    /// <param name="canonicalPrefix">Segment A.</param>
    /// <param name="seqNo">The row's sequence number within its chain.</param>
    /// <param name="recordedAtTicks">100-nanosecond ticks since the Unix epoch, as stored by the ledger.</param>
    /// <returns>The 32-byte row hash.</returns>
    public static byte[] ComputeRowHash(
        ReadOnlySpan<byte> prevHash, ReadOnlySpan<byte> canonicalPrefix, long seqNo, long recordedAtTicks)
    {
        var body = new byte[prevHash.Length + canonicalPrefix.Length + 16];
        prevHash.CopyTo(body);
        canonicalPrefix.CopyTo(body.AsSpan(prevHash.Length));
        var tail = body.AsSpan(prevHash.Length + canonicalPrefix.Length);
        BinaryPrimitives.WriteInt64BigEndian(tail, seqNo);
        BinaryPrimitives.WriteInt64BigEndian(tail[8..], recordedAtTicks);
        return SHA256.HashData(body);
    }

    /// <summary>
    /// The C# twin of the ledger's <c>RecordedAtTicks</c> computed column: 100-nanosecond ticks since the Unix
    /// epoch. Kept as an explicit integer rather than any database time format, whose binary layout is an
    /// implementation detail we must not hash.
    /// </summary>
    /// <param name="utc">A UTC instant.</param>
    /// <returns>Ticks since 1970-01-01T00:00:00Z.</returns>
    public static long ToUnixTicks(DateTime utc) => utc.Ticks - DateTime.UnixEpoch.Ticks;

    // The interface is implemented EXPLICITLY so the instance members can never take part in overload
    // resolution against the static algorithm above — one name, one meaning at every call site.

    /// <inheritdoc />
    byte[] IAgentActionCanonicalizer.BuildPrefix(Guid appId, AgentActionRecord record, byte recordKind)
        => BuildPrefix(appId, record, recordKind);

    /// <inheritdoc />
    byte[] IAgentActionCanonicalizer.BuildPrefix(AgentLedgerArchiveRow row) => BuildPrefix(row);

    /// <inheritdoc />
    byte[] IAgentActionCanonicalizer.ComputeRowHash(
        ReadOnlySpan<byte> prevHash, ReadOnlySpan<byte> canonicalPrefix, long seqNo, long recordedAtTicks)
        => ComputeRowHash(prevHash, canonicalPrefix, seqNo, recordedAtTicks);

    /// <summary>
    /// THE FROZEN FIELD ORDER — 23 fields, in exactly this sequence. It exists in ONE place on purpose: the
    /// write path and the verify path must be incapable of drifting apart, because a drift between them would
    /// present itself as "the archive is broken" rather than as a bug in us.
    /// </summary>
    private static byte[] BuildCore(
        byte hashVersion, Guid appId, string tenantId, byte recordKind, Guid eventId, string occurredAtUtcText,
        string agentId, string? agentVersion, string? modelId, byte authorityKind, int? onBehalfOfUserId,
        string? sessionId, string? invocationId, string? correlationId, string actionType, string? targetType,
        string? targetId, byte decision, byte outcome, byte[]? inputDigest, byte[]? outputDigest,
        string? errorCode, byte[]? errorDigest)
    {
        using var buffer = new MemoryStream(256);

        buffer.WriteByte(hashVersion);                                   //  1 HashVersion
        WriteRaw(buffer, appId.ToByteArray(bigEndian: true));            //  2 AppId
        WriteText(buffer, tenantId);                                     //  3 TenantId
        buffer.WriteByte(recordKind);                                    //  4 RecordKind
        WriteRaw(buffer, eventId.ToByteArray(bigEndian: true));          //  5 EventId
        WriteText(buffer, occurredAtUtcText);                            //  6 OccurredAtUtc
        WriteText(buffer, agentId);                                      //  7 AgentId
        WriteText(buffer, agentVersion);                                 //  8 AgentVersion
        WriteText(buffer, modelId);                                      //  9 ModelId
        buffer.WriteByte(authorityKind);                                 // 10 AuthorityKind
        WriteNullableInt32(buffer, onBehalfOfUserId);                    // 11 OnBehalfOfUserId
        WriteText(buffer, sessionId);                                    // 12 SessionId
        WriteText(buffer, invocationId);                                 // 13 InvocationId
        WriteText(buffer, correlationId);                                // 14 CorrelationId
        WriteText(buffer, actionType);                                   // 15 ActionType
        WriteText(buffer, targetType);                                   // 16 TargetType
        WriteText(buffer, targetId);                                     // 17 TargetId
        buffer.WriteByte(decision);                                      // 18 Decision
        buffer.WriteByte(outcome);                                       // 19 Outcome
        WriteBlob(buffer, inputDigest);                                  // 20 InputDigest
        WriteBlob(buffer, outputDigest);                                 // 21 OutputDigest
        WriteText(buffer, errorCode);                                    // 22 ErrorCode
        WriteBlob(buffer, errorDigest);                                  // 23 ErrorDigest

        // NOT hashed, deliberately: OnBehalfOfUserName and ErrorMessage (redactable projection columns), the
        // Fold* columns, and Signature/SignatureAlgo. They are protected by the immutability triggers only.

        return buffer.ToArray();
    }

    private static byte[]? FromHex(string? hex) => hex is null ? null : Convert.FromHexString(hex);

    /// <summary>Normalises to UTC and formats as the round-trip "O" form with 7 fraction digits.</summary>
    private static string RoundTrip(DateTime value)
    {
        var utc = value.Kind switch
        {
            DateTimeKind.Utc => value,
            DateTimeKind.Local => value.ToUniversalTime(),
            // Unspecified is read back from DATETIME2, which the ledger only ever stores in UTC.
            _ => DateTime.SpecifyKind(value, DateTimeKind.Utc),
        };
        return utc.ToString("O", CultureInfo.InvariantCulture);
    }

    private static void WriteRaw(Stream target, byte[] value) => target.Write(value, 0, value.Length);

    /// <summary>4-byte LITTLE-endian signed length. -1 means NULL; 0 means empty — the two must never collide.</summary>
    private static void WriteLength(Stream target, int length)
    {
        Span<byte> bytes = stackalloc byte[4];
        BinaryPrimitives.WriteInt32LittleEndian(bytes, length);
        target.Write(bytes);
    }

    private static void WriteText(Stream target, string? value)
    {
        if (value is null) { WriteLength(target, -1); return; }
        var bytes = Encoding.UTF8.GetBytes(value);
        WriteLength(target, bytes.Length);   // BYTES, not characters — multi-byte text must not be mis-counted
        WriteRaw(target, bytes);
    }

    private static void WriteBlob(Stream target, byte[]? value)
    {
        if (value is null) { WriteLength(target, -1); return; }
        WriteLength(target, value.Length);
        WriteRaw(target, value);
    }

    private static void WriteNullableInt32(Stream target, int? value)
    {
        if (value is null) { WriteLength(target, -1); return; }
        WriteLength(target, 4);
        Span<byte> bytes = stackalloc byte[4];
        BinaryPrimitives.WriteInt32BigEndian(bytes, value.Value);   // BIG-endian, signed
        target.Write(bytes);
    }
}
