// Copyright (C) 2026 Orhan Özşahin — Asdamir.
// Licensed under the GNU Lesser General Public License v3.0. See LICENSE.
// SPDX-License-Identifier: LGPL-3.0-or-later
//
// This file is part of the Asdamir open core. It is free software: you can redistribute it
// and/or modify it under the terms of the GNU Lesser General Public License as published by the
// Free Software Foundation, either version 3 of the License, or (at your option) any later
// version. It is distributed WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU LGPL for more details.

using System.Buffers.Binary;
using System.Globalization;
using System.Security.Cryptography;
using System.Text;

namespace Asdamir.Core.AgentAudit;

/// <summary>
/// Builds the FROZEN canonical byte serialisation that the agent action ledger's hash chain is computed over.
///
/// <para><b>This type is the single most change-sensitive thing in the feature.</b> Every hash ever written is
/// a function of these bytes, so a "harmless tidy-up" here silently invalidates the entire history: rows that
/// were never touched stop verifying. The layout is therefore FROZEN per <see cref="HashVersion1"/> and pinned
/// by committed golden vectors that were generated by an INDEPENDENT implementation (a Python script under
/// <c>tests/Asdamir.Core.Tests/GoldenVectors/</c>). If a change is genuinely needed, it takes a NEW
/// HashVersion — old rows keep verifying under theirs — never an edit to an existing one.</para>
///
/// <para><b>Hybrid by design.</b> This builds SEGMENT A only (fields 1-23, everything the client knows). The
/// two fields only the server can know — SeqNo and the server-side RecordedAt — are appended by
/// <c>dbo.AgentActionLedger_Append</c> while it holds the per-chain lock. That is what makes the sequence race
/// unwinnable outside the database.</para>
///
/// <para><b>Where this runs.</b> Server-side, in the control plane, not in the calling application: field 2 is
/// the AppId, and the AppId is resolved from the ingest service token rather than from the payload, so the
/// client is structurally unable to build its own prefix.</para>
/// </summary>
internal static class AgentActionCanonicalizer
{
    /// <summary>The only canonicalization version in existence. Its layout must never change.</summary>
    internal const byte HashVersion1 = 1;

    /// <summary>A chain's first row is anchored on 32 zero bytes.</summary>
    internal static ReadOnlySpan<byte> ZeroHash => new byte[32];

    /// <summary>RecordKind 0 — an ordinary agent action event.</summary>
    internal const byte RecordKindEvent = 0;

    /// <summary>
    /// Builds segment A for <paramref name="record"/> in the chain scoped to <paramref name="appId"/>.
    /// </summary>
    /// <param name="appId">The chain's application id — resolved server-side, never taken from the payload.</param>
    /// <param name="record">The action being recorded.</param>
    /// <param name="recordKind">0 = Event, 1 = Seal. Tombstones carry no prefix at all.</param>
    /// <param name="hashVersion">The canonicalization version; the first byte of the result, which the
    /// stored procedure cross-checks against its own parameter so a wiring bug cannot poison a chain.</param>
    /// <returns>The canonical prefix bytes.</returns>
    internal static byte[] BuildPrefix(
        Guid appId, AgentActionRecord record, byte recordKind = RecordKindEvent, byte hashVersion = HashVersion1)
    {
        ArgumentNullException.ThrowIfNull(record);

        using var buffer = new MemoryStream(256);

        buffer.WriteByte(hashVersion);                                          //  1 HashVersion
        WriteRaw(buffer, appId.ToByteArray(bigEndian: true));                   //  2 AppId
        WriteText(buffer, record.TenantId);                                     //  3 TenantId
        buffer.WriteByte(recordKind);                                           //  4 RecordKind
        WriteRaw(buffer, record.EventId.ToByteArray(bigEndian: true));          //  5 EventId
        WriteText(buffer, RoundTrip(record.OccurredAtUtc));                     //  6 OccurredAtUtc
        WriteText(buffer, record.AgentId);                                      //  7 AgentId
        WriteText(buffer, record.AgentVersion);                                 //  8 AgentVersion
        WriteText(buffer, record.ModelId);                                      //  9 ModelId
        buffer.WriteByte((byte)record.AuthorityKind);                           // 10 AuthorityKind
        WriteNullableInt32(buffer, record.OnBehalfOfUserId);                    // 11 OnBehalfOfUserId
        WriteText(buffer, record.SessionId);                                    // 12 SessionId
        WriteText(buffer, record.InvocationId);                                 // 13 InvocationId
        WriteText(buffer, record.CorrelationId);                                // 14 CorrelationId
        WriteText(buffer, record.ActionType);                                   // 15 ActionType
        WriteText(buffer, record.TargetType);                                   // 16 TargetType
        WriteText(buffer, record.TargetId);                                     // 17 TargetId
        buffer.WriteByte((byte)record.Decision);                                // 18 Decision
        buffer.WriteByte((byte)record.Outcome);                                 // 19 Outcome
        WriteBlob(buffer, record.InputDigest);                                  // 20 InputDigest
        WriteBlob(buffer, record.OutputDigest);                                 // 21 OutputDigest
        WriteText(buffer, record.ErrorCode);                                    // 22 ErrorCode
        WriteBlob(buffer, record.ErrorDigest);                                  // 23 ErrorDigest

        // NOT hashed, deliberately: OnBehalfOfUserName and ErrorMessage (redactable projection columns), the
        // Fold* columns, and Signature/SignatureAlgo. They are protected by the immutability triggers only.

        return buffer.ToArray();
    }

    /// <summary>
    /// Recomputes a row hash: <c>SHA-256(PrevHash || prefix || SeqNo(BE8) || RecordedAtTicks(BE8))</c>. Used by
    /// the canonical verifier; the appending procedure computes the identical value in T-SQL.
    /// </summary>
    /// <param name="prevHash">The previous row's hash (32 bytes), or 32 zero bytes for a chain's first row.</param>
    /// <param name="canonicalPrefix">Segment A.</param>
    /// <param name="seqNo">The row's sequence number within its chain.</param>
    /// <param name="recordedAtTicks">100-nanosecond ticks since the Unix epoch, as stored by the ledger.</param>
    /// <returns>The 32-byte row hash.</returns>
    internal static byte[] ComputeRowHash(
        ReadOnlySpan<byte> prevHash, ReadOnlySpan<byte> canonicalPrefix, long seqNo, long recordedAtTicks)
    {
        var body = new byte[prevHash.Length + canonicalPrefix.Length + 16];
        prevHash.CopyTo(body);
        canonicalPrefix.CopyTo(body.AsSpan(prevHash.Length));
        var tail = body.AsSpan(prevHash.Length + canonicalPrefix.Length);
        BinaryPrimitives.WriteInt64BigEndian(tail, seqNo);
        BinaryPrimitives.WriteInt64BigEndian(tail[8..], recordedAtTicks);
        return SHA256.HashData(body);
    }

    /// <summary>
    /// The C# twin of the ledger's <c>RecordedAtTicks</c> computed column: 100-nanosecond ticks since the Unix
    /// epoch. Kept as an explicit integer rather than any database time format, whose binary layout is an
    /// implementation detail we must not hash.
    /// </summary>
    /// <param name="utc">A UTC instant.</param>
    /// <returns>Ticks since 1970-01-01T00:00:00Z.</returns>
    internal static long ToUnixTicks(DateTime utc) => utc.Ticks - DateTime.UnixEpoch.Ticks;

    /// <summary>Normalises to UTC and formats as the round-trip "O" form with 7 fraction digits.</summary>
    private static string RoundTrip(DateTime value)
    {
        var utc = value.Kind switch
        {
            DateTimeKind.Utc => value,
            DateTimeKind.Local => value.ToUniversalTime(),
            // Unspecified is read back from DATETIME2, which the ledger only ever stores in UTC.
            _ => DateTime.SpecifyKind(value, DateTimeKind.Utc),
        };
        return utc.ToString("O", CultureInfo.InvariantCulture);
    }

    private static void WriteRaw(Stream target, byte[] value) => target.Write(value, 0, value.Length);

    /// <summary>4-byte LITTLE-endian signed length. -1 means NULL; 0 means empty — the two must never collide.</summary>
    private static void WriteLength(Stream target, int length)
    {
        Span<byte> bytes = stackalloc byte[4];
        BinaryPrimitives.WriteInt32LittleEndian(bytes, length);
        target.Write(bytes);
    }

    private static void WriteText(Stream target, string? value)
    {
        if (value is null) { WriteLength(target, -1); return; }
        var bytes = Encoding.UTF8.GetBytes(value);
        WriteLength(target, bytes.Length);   // BYTES, not characters — multi-byte text must not be mis-counted
        WriteRaw(target, bytes);
    }

    private static void WriteBlob(Stream target, byte[]? value)
    {
        if (value is null) { WriteLength(target, -1); return; }
        WriteLength(target, value.Length);
        WriteRaw(target, value);
    }

    private static void WriteNullableInt32(Stream target, int? value)
    {
        if (value is null) { WriteLength(target, -1); return; }
        WriteLength(target, 4);
        Span<byte> bytes = stackalloc byte[4];
        BinaryPrimitives.WriteInt32BigEndian(bytes, value.Value);   // BIG-endian, signed
        target.Write(bytes);
    }
}
